/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NuevaPartida.java
 *
 * Created on 23-abr-2011, 23:28:02
 */
package adivinaelnumerogui;

import org.jdesktop.application.Action;
import org.jdesktop.application.Application;

/**
 *
 * @author FutuzorMekkla
 */
public class NuevaPartida extends javax.swing.JDialog {

    /** Creates new form NuevaPartida */
    public NuevaPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        OpcFacil = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        OpcMedio = new javax.swing.JRadioButton();
        OpcDificil = new javax.swing.JRadioButton();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(adivinaelnumerogui.AdivinaElNumeroGUIApp.class).getContext().getResourceMap(NuevaPartida.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buttonGroup1.add(OpcFacil);
        OpcFacil.setFont(resourceMap.getFont("Etiqueta")); // NOI18N
        OpcFacil.setSelected(true);
        OpcFacil.setText(resourceMap.getString("OpcFacil.text")); // NOI18N
        OpcFacil.setName("OpcFacil"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        buttonGroup1.add(OpcMedio);
        OpcMedio.setFont(resourceMap.getFont("Etiqueta")); // NOI18N
        OpcMedio.setText(resourceMap.getString("OpcMedio.text")); // NOI18N
        OpcMedio.setName("OpcMedio"); // NOI18N

        buttonGroup1.add(OpcDificil);
        OpcDificil.setFont(resourceMap.getFont("Etiqueta")); // NOI18N
        OpcDificil.setText(resourceMap.getString("OpcDificil.text")); // NOI18N
        OpcDificil.setName("OpcDificil"); // NOI18N

        BtnAceptar.setFont(resourceMap.getFont("Etiqueta")); // NOI18N
        BtnAceptar.setText(resourceMap.getString("BtnAceptar.text")); // NOI18N
        BtnAceptar.setName("BtnAceptar"); // NOI18N
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(adivinaelnumerogui.AdivinaElNumeroGUIApp.class).getContext().getActionMap(NuevaPartida.class, this);
        BtnCancelar.setAction(actionMap.get("cerrarDialogo")); // NOI18N
        BtnCancelar.setFont(resourceMap.getFont("Etiqueta")); // NOI18N
        BtnCancelar.setText(resourceMap.getString("BtnCancelar.text")); // NOI18N
        BtnCancelar.setName("BtnCancelar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OpcDificil)
                    .addComponent(OpcMedio)
                    .addComponent(jLabel1)
                    .addComponent(OpcFacil)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCancelar)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OpcFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OpcMedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OpcDificil)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptar)
                    .addComponent(BtnCancelar))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        dispose();
        if (OpcFacil.isSelected()) {
            AdivinaElNumeroGUIApp.getApplication().getPar().setNumDificultad(1);
        } else if (OpcMedio.isSelected()) {
            AdivinaElNumeroGUIApp.getApplication().getPar().setNumDificultad(2);
        } else {
            AdivinaElNumeroGUIApp.getApplication().getPar().setNumDificultad(3);
        }

        AdivinaElNumeroGUIApp.getApplication().getPar().setPartidaCreada(true);
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        OpcFacil.setSelected(true);
        OpcMedio.setSelected(false);
        OpcDificil.setSelected(false);
    }//GEN-LAST:event_formWindowClosed

    @Action
    public void cerrarDialogo() {
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JRadioButton OpcDificil;
    private javax.swing.JRadioButton OpcFacil;
    private javax.swing.JRadioButton OpcMedio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
